### ISSUE TITLE
Bug: Microsoft Edge isn't IE

### ISSUE THREAD

**Issue by PaintNinja** [nfriedly/user-agent.io#2]
When visiting whatsmyua.com in Microsoft Edge, the page thinks that the browser's name is IE.

**Comment by nfriedly** [comment]
This is fixed in https://github.com/faisalman/ua-parser-js/pull/113 we're just waiting on a new npm release.

**Comment by PaintNinja** [comment]
Thanks! :)

**Comment by nfriedly** [comment]
It looks like this is now fixed: http://www.whatsmyua.com/#Mozilla/5.0%20(Windows%20NT%2010.0)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.10136
