### ISSUE TITLE
Bug: waterfox isn't firefox

### ISSUE THREAD

**Issue by moon-chilled** [nfriedly/user-agent.io#4]
UA string: Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.1.0 Waterfox/50.1.0

http://www.whatsmyua.com/#Mozilla/5.0%20(X11;%20Linux%20x86_64;%20rv:50.0)%20Gecko/20100101%20Firefox/50.1.0%20Waterfox/50.1.0

**Comment by nfriedly** [comment]
True, although it looks pretty similar to me.

Regardless, this site uses https://www.npmjs.com/package/ua-parser under the hood, which uses browscap under it's hood, so it looks like you already filed another ticket in the right place.

I'm going to close this ticket, and we can track it on that one.

cc @toby @ua-parser @browscap
