### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by JakeChampion** [nfriedly/user-agent.io#5]
Hi, I was wondering if you would be interested in hosting this over HTTPS at all? It looks to be a github pages host website, this blog post guides through how to have HTTPS on a custom domain using github pages -- https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

Thanks for the great project by the way! We link to it from https://polyfill.io :-D

**Comment by nfriedly** [comment]
I never really considered HTTPS for this site, but that's an interesting idea. It looks like it's basically switching hosting to cloudflare, which I'm not entirely against, but I'm not sure it's worth the trouble in this case. I'll think it over a bit more, though.

Thanks for the idea and the link either way!
